[package]
name = "bevy_shaman_world"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bevy.workspace = true
bevy_shaman_core = { path = "../bevy_shaman_core" }
bevy_shaman_items = { path = "../bevy_shaman_items" }
serde.workspace = true
rand.workspace = true

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "world_generation"
harness = false
