[package]
name = "bevy_shaman_monitoring"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bevy = { workspace = true }
serde = { workspace = true }
prometheus = { workspace = true }
sentry = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
