[package]
name = "bevy_shaman_tutorial"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bevy.workspace = true
bevy_shaman_core = { path = "../bevy_shaman_core" }
bevy_shaman_combat = { path = "../bevy_shaman_combat" }
bevy_shaman_monsters = { path = "../bevy_shaman_monsters" }
bevy_shaman_world = { path = "../bevy_shaman_world" }
bevy_shaman_ui = { path = "../bevy_shaman_ui" }
bevy_shaman_save = { path = "../bevy_shaman_save" }
bevy_shaman_story = { path = "../bevy_shaman_story" }
serde.workspace = true
serde_json.workspace = true
rand.workspace = true
